services:
  - type: web
    name: lms-django
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements/production.txt && python manage.py collectstatic --noinput
    startCommand: bash start.sh
    healthCheckPath: /
    region: oregon
    pythonVersion: 3.11
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: ${{ RENDER_EXTERNAL_HOSTNAME }}
      - key: DATABASE_URL
        value: postgresql://mydb:aBzQVIUuJyRoZNp7iDr8AzYYO1C1OHU8D@dpg-d98htqt7vvec7391ligu&-a.oregon-postgres.render.com/mydb_n2zh?sslmode=require
      - key: DB_NAME
        value: mydb_n2zh
      - key: DB_USER
        value: mydb
      - key: DB_PASSWORD
        value: aBzQVIUuJyRoZNp7iDr8AzYYO1C1OHU8D
      - key: DB_HOST
        value: dpg-d98htqt7vvec7391ligu&-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DJANGO_SETTINGS_MODULE
        value: SMS.settings
      - key: USE_S3
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"

databases:
  - name: lms-db
    databaseName: lmsdb
    plan: free
    postgresSQLVersion: 14
